pokedex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.home, name='home'),
    path('dex/', views.DexView.as_view(), name='dex'),
    path('<int:number>/', views.ProfileView.as_view(), name='profile')
]

website/models.py
from django.db import models


class Type(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return f'Type({self.name})'


class Pokemon(models.Model):
    number = models.IntegerField(unique=True)
    name = models.CharField(max_length=15, unique=True)
    primary_type = models.ForeignKey(Type, related_name='primary', on_delete=models.CASCADE)
    secondary_type = models.ForeignKey(Type, related_name='secondary', on_delete=models.CASCADE, null=True, blank=True)
    height = models.IntegerField()
    weight = models.IntegerField()
    genus = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    image = models.CharField(max_length=10, unique=True)
    hp = models.IntegerField()
    attack = models.IntegerField()
    defense = models.IntegerField()
    special = models.IntegerField()
    speed = models.IntegerField()
    evolves_from = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, db_index=True)

    def types(self):
        return [self.primary_type, self.secondary_type]

    def height_in_m(self):
        return self.height / 10.0

    def height_in_in(self):
        return self.height_in_m() / 0.0254

    def height_in_ft(self):
        return self.height_in_in() // 12, self.height_in_in() % 12

    def weight_in_kg(self):
        return self.weight / 10.0

    def weight_in_lb(self):
        return self.weight_in_kg() * 2.2

    def __str__(self):
        return f'Pokemon({self.name})'

website/views.py
from django.shortcuts import render
from django.views import generic

from website.models import Pokemon


def home(request):
    return render(request, 'website/home.html')


class DexView(generic.ListView):
    template_name = 'website/dex.html'
    context_object_name = 'mon_list'

    def get_queryset(self):
        return Pokemon.objects.filter(name__startswith=self.request.GET.get('q', '')).order_by('number')


class ProfileView(generic.DetailView):
    model = Pokemon
    slug_field = 'number'
    slug_url_kwarg = 'number'
    template_name = 'website/profile.html'

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}<title>Pokédex</title>{% endblock %}
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css"/>
        <style>
            body {
                display        : flex;
                min-height     : 100vh;
                flex-direction : column;
            }

            #wrapper {
                flex : 1;
            }

            .mon-avatar {
            padding          : 20px;
            background-color : lightgrey;
            }

            .tag.type {
                color : white;
            }

            .tag.type.grass-type {
                background-color : green;
            }

            .tag.type.fire-type {
                background-color : #fa5902;
            }

            .tag.type.ground-type {
                background-color : #e3cd5f;
            }

            .tag.type.electric-type {
                background-color : #e8e109;
            }

            .tag.type.water-type {
                background-color : #5f62f5;
            }

            .tag.type.rock-type {
                background-color : #a1852b;
            }

            .tag.type.flying-type {
                background-color : #a882f5;
            }

            .tag.type.ice-type {
                background-color : turquoise;
            }

            .tag.type.normal-type {
                background-color : #adad86;
            }

            .tag.type.bug-type {
                background-color : #a4cf23;
            }

            .tag.type.ghost-type {
                background-color : #5f496e;
            }

            .tag.type.fighting-type {
                background-color : brown;
            }

            .tag.type.dragon-type {
                background-color : #2318ba;
            }

            .tag.type.psychic-type {
                background-color : #e329b1;
            }

            .tag.type.poison-type {
                background-color : purple;
            }
        </style>
        {% block style %}{% endblock %}
        {% load static %}
        <link rel="shortcut icon" href="{% static 'website/images/favicon.ico' %}"/>
        <script>
            document.addEventListener('DOMContentLoaded', () => {

              // Get all "navbar-burger" elements
              const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

              // Check if there are any navbar burgers
              if ($navbarBurgers.length > 0) {

                // Add a click event on each of them
                $navbarBurgers.forEach( el => {
                  el.addEventListener('click', () => {

                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');

                  });
                });
              }

            });
        </script>
    </head>
    <body>
        <nav class="navbar is-light" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="{% static 'website/images/icon.png' %}" height="28" alt="Logo">
                </a>

                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                   data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="/">
                        Home
                    </a>

                    <a class="navbar-item" href="{% url 'website:dex' %}">
                        Dex
                    </a>

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            More
                        </a>

                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="https://www.youtube.com/user/TraceurJames" target="_blank">
                                YouTube
                            </a>
                            <a class="navbar-item" href="https://www.github.com/jsmithdataanalytics" target="_blank">
                                GitHub
                            </a>
                            <hr class="navbar-divider">
                            <a class="navbar-item" href="mailto:jsmithdataanalytics@gmail.com">
                                Contact
                            </a>
                        </div>
                    </div>
                </div>
                <div class="navbar-end">
                    <a class="navbar-item" href="/">
                        <figure>
                            <img src="{% static 'website/images/logo.png' %}" alt="Pokédex"/>
                        </figure>
                    </a>
                </div>
            </div>
        </nav>
        <div id="wrapper">
            {% block content %}{% endblock %}
        </div>
        <footer class="footer">
            <div class="content has-text-centered">
                <p>
                    <strong>Pokédex</strong> by <a target="_blank" href="https://www.github.com/jsmithdataanalytics">James
                    Smith</a>.
                    The source code is licensed <a target="_blank"
                                                   href="http://opensource.org/licenses/mit-license.php">MIT</a>.
                </p>
            </div>
        </footer>
    </body>
</html> 

website/templates/website/dex.html
{% extends "website/base.html" %}
{% block style %}
    <style>
        #logo {
            margin-bottom : 10%;
        }

        #search {
            margin-top : 20px
        }
    </style>
{% endblock %}
{% block content %}
    {% load static %}
    <section class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-half">
                    <figure id="logo">
                        <img src="{% static 'website/images/logo.png' %}" alt="Pokédex"/>
                        <form action="{% url 'website:dex' %}" method="get" id="search">
                            <div class="field">
                                <div class="control">
                                    <label>
                                        <input class="input is-rounded" type="text" placeholder="Search the dex" name="q">
                                    </label>
                                </div>
                            </div>
                        </form>
                    </figure>
                </div>
            </div>
        </div>
        <div class="container">
            {% if not mon_list %}
                <div class="columns is-centered">
                    <div class="column is-half has-text-centered">
                        <p><strong>No results</strong></p>
                    </div>
                </div>
            {% else %}
                <div class="tile is-ancestor">
                    <div class="tile is-vertical">
                        <div class="tile">
                            {% for mon in mon_list %}
                                <div class="tile is-parent is-3">
                                    <div class="tile is-child">
                                        <a href="{% url 'website:profile' mon.number %}">
                                            <div class="card">
                                                <div class="card-image mon-avatar">
                                                    <figure class="image is-square">
                                                        <img src="{% with 'website/images/mons/'|add:mon.image as image_static %}{% static image_static %}{% endwith %}" alt="{{ mon.name }}">
                                                    </figure>
                                                </div>
                                                <div class="card-content">
                                                    <div class="media">
                                                        <div class="media-content">
                                                            {% if mon.number == 83 %}
                                                                <p class="title is-4">#{{ mon.number }} Farfetch'd</p>
                                                            {% else %}
                                                                <p class="title is-4">
                                                                    #{{ mon.number }} {{ mon.name.title }}</p>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                    <div class="tile is-ancestor">
                                                        {% for type in mon.types %}
                                                            <div class="tile is-parent">
                                                                {% if type %}
                                                                    <article class="tile is-child tag {{ type.name }}-type type">{{ type.name.title }}</article>
                                                                {% else %}
                                                                    <article class="tile is-child"></article>
                                                                {% endif %}
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <!-- if last column in row -->
                                {% if forloop.counter|divisibleby:"4" and not forloop.last %}
                                    </div>
                                    <div class="tile">
                                {% endif %}
                            {% endfor %}
                            </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>
{% endblock %}

website/templates/website/home.html
{% extends "website/base.html" %}
{% block style %}
    <style>#logo {
        margin-top : 25%;
    }</style>
{% endblock %}
{% block content %}
    {% load static %}
    <section class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-half">
                    <figure id="logo">
                        <img src="{% static 'website/images/logo.png' %}" alt="Pokédex"/>
                    </figure>
                </div>
            </div>
            <div class="columns is-centered search">
                <div class="column is-half">
                    <form action="{% url 'website:dex' %}" method="get">
                        <div class="field">
                            <div class="control">
                                <label>
                                    <input class="input is-rounded" type="text" placeholder="Search the dex" name="q">
                                </label>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

website/templates/website/index.html
{% extends "website/base.html" %}
{% block content %}
    <h1 class="title is-1">Pokédex</h1>
    <div class="content">
        <ol type="1">
            {% for mon in mon_list %}
                <li><a href="{% url 'website:profile' mon.number %}">{{ mon.name.upper }}</a></li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

website/templates/website/profile.html
{% extends "website/base.html" %}
{% block content %}
    {% load static %}
    <section class="section">
        <div class="container">
            <div class="tile is-ancestor">
                <div class="tile is-vertical">
                    <div class="tile is-parent">
                        <div class="tile is-child box">
                            <div class="tile is-ancestor">
                                <div class="tile is-parent is-4">
                                    <div class="tile is-child">
                                        <figure class="image is-square">
                                            <img class="mon-avatar" src="
                                                    {% with 'website/images/mons/'|add:pokemon.image as image_static %}{% static image_static %}{% endwith %}"
                                                 alt="{{ pokemon.name }}">
                                        </figure>
                                    </div>
                                </div>
                                <div class="tile is-vertical">
                                    <div class="tile is-parent">
                                        <div class="tile is-child content">
                                            {% if pokemon.number == 83 %}
                                                <p class="title is-1">#{{ pokemon.number }} Farfetch'd</p>
                                            {% else %}
                                                <p class="title is-1">
                                                    #{{ pokemon.number }} {{ pokemon.name.title }}</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="tile is-5">
                                        {% for type in pokemon.types %}
                                            <div class="tile is-parent">
                                                {% if type %}
                                                    <article
                                                            class="tile is-child tag {{ type.name }}-type type">{{ type.name.title }}</article>
                                                {% else %}
                                                    <article class="tile is-child"></article>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="tile is-parent">
                                        <div class="tile is-child notification">
                                            <p class="title is-6">{{ pokemon.genus }}</p>
                                            <p>{{ pokemon.description }}</p>
                                        </div>
                                    </div>
                                    <div class="tile">
                                        <div class="tile is-parent">
                                            <div class="tile is-child notification">
                                                <p class="title is-6">Physical Characteristics</p>
                                                <p>Height: {{ pokemon.height_in_m|floatformat:1 }} m / {{ pokemon.height_in_ft|first|floatformat:0 }}'{{ pokemon.height_in_ft|last|floatformat:0 }}"</p>
                                                <p>Weight: {{ pokemon.weight_in_kg|floatformat:1 }} kg / {{ pokemon.weight_in_lb|floatformat:1 }} lb</p>
                                            </div>
                                        </div>
                                        <div class="tile is-parent">
                                            <div class="tile is-child notification">
                                                <p class="title is-6">Base Stats</p>
                                                <div class="columns">
                                                    <div class="column">
                                                        <p>HP: {{ pokemon.hp }}</p>
                                                        <p>Attack: {{ pokemon.attack }}</p>
                                                        <p>Defense: {{ pokemon.defense }}</p>
                                                    </div>
                                                    <div class="column">
                                                        <p>Special: {{ pokemon.special }}</p>
                                                        <p>Speed: {{ pokemon.speed }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tile">
                        <div class="tile is-parent">
                            <div class="tile is-child">
                                {% if pokemon.evolves_from %}
                                    <div class="notification">
                                        <p><strong>Evolves From</strong></p>
                                        <div class="tile is-parent">
                                            <div class="tile is-child">
                                                <figure class="image is-64x64">
                                                    <a href="{% url 'website:profile' pokemon.evolves_from.number %}">
                                                        <img src="{% with 'website/images/mons/'|add:pokemon.evolves_from.image as image_static %}{% static image_static %}{% endwith %}" alt="{{ pokemon.evolves_from.name }}">
                                                    </a>
                                                </figure>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="tile is-parent">
                            <div class="tile is-child">
                                {% if pokemon.pokemon_set.all %}
                                    <div class="notification">
                                        <p><strong>Evolves To</strong></p>
                                        <div class="tile">
                                            {% for evo in pokemon.pokemon_set.all %}
                                                <div class="tile is-parent">
                                                    <div class="tile is-child">
                                                        <figure class="image is-64x64">
                                                            <a href="{% url 'website:profile' evo.number %}">
                                                                <img src="{% with 'website/images/mons/'|add:evo.image as image_static %}{% static image_static %}{% endwith %}" alt="{{ evo.name }}">
                                                            </a>
                                                        </figure>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}